---
# Include a clusterrole for the kube-controllers component,
# and bind it to the flannel-migration-controller serviceaccount.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flannel-migration-controller
rules:
  # Nodes are watched to monitor for deletions.
  - apiGroups: [""]
    resources:
      - nodes
    verbs:
      - watch
      - list
      - get
      - update
  # Nodes are watched to monitor for deletions.
  - apiGroups: [""]
    resources:
      - nodes/status
    verbs:
      - get
      - update
  # Pods are queried to check for existence.
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - delete
  # Daemonset are watched to monitor for deletions.
  - apiGroups: ["apps", "extensions"]
    resources:
      - daemonsets
    verbs:
      - get
      - delete
      - update
  # IPAM resources are manipulated when nodes are deleted.
  - apiGroups: ["crd.projectcalico.org"]
    resources:
      - ippools
    verbs:
      - get
      - list
      - create
  - apiGroups: ["crd.projectcalico.org"]
    resources:
      - ipamconfigs
      - blockaffinities
      - ipamblocks
      - ipamhandles
    verbs:
      - get
      - list
      - create
      - update
      - delete
  # Needs access to update clusterinformations.
  - apiGroups: ["crd.projectcalico.org"]
    resources:
      - clusterinformations
    verbs:
      - get
      - create
      - update
  # Needs access to update felixconfigurations.
  - apiGroups: ["crd.projectcalico.org"]
    resources:
      - felixconfigurations
    verbs:
      - get
      - create
      - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flannel-migration-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flannel-migration-controller
subjects:
- kind: ServiceAccount
  name: flannel-migration-controller
  namespace: kube-system

---
# See https://github.com/projectcalico/kube-controllers
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flannel-migration-controller
  namespace: kube-system
  labels:
    k8s-app: flannel-migration-controller
spec:
  # The controllers can only have a single active instance.
  replicas: 1
  selector:
    matchLabels:
      k8s-app: flannel-migration-controller
  strategy:
    type: Recreate
  template:
    metadata:
      name: flannel-migration-controller
      namespace: kube-system
      labels:
        k8s-app: flannel-migration-controller
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      tolerations:
        # Mark the pod as a critical add-on for rescheduling.
        - key: CriticalAddonsOnly
          operator: Exists
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      serviceAccountName: flannel-migration-controller
      priorityClassName: system-cluster-critical
      containers:
        - name: flannel-migration-controller
          image: songtjiang/kube-controllers:latest
          env:
            # Choose which controllers to run.
            - name: ENABLED_CONTROLLERS
              value: flannelmigration
            - name: DATASTORE_TYPE
              value: kubernetes
            - name: FLANNEL_MTU
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: veth_mtu
            - name: FLANNEL_NETWORK
              value: "10.244.0.0/16"
            - name: FLANNEL_DAEMONSET_NAME
              value: "kube-flannel-ds"
          readinessProbe:
            exec:
              command:
              - /usr/bin/check-status
              - -r

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: flannel-migration-controller
  namespace: kube-system

